server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://39.105.139.200:3306/securitydemo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Xt774071!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 39.105.139.200
    port: 6379
    password: Xt774071!
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml